### ISSUE TITLE
Argo workflows does not work

### ISSUE THREAD

**Issue by shaharl-sternum** [argoproj/argo-helm#1360]
### Describe the bug

After upgrading to version 3.3.8 I can't run workflows.
The main screen says Nothing to show and I get the following error from the logs button in the UI:

```log
Stack Trace
TypeError: Cannot read properties of undefined (reading 'undefined')
    at t.WorkflowLogsViewer (http://localhost:2746/main.f4aed2fe1c9a4487ef2e.js:240:76616)
    at $i (http://localhost:2746/main.f4aed2fe1c9a4487ef2e.js:531:52993)
    at Io (http://localhost:2746/main.f4aed2fe1c9a4487ef2e.js:531:65197)
    at qa (http://localhost:2746/main.f4aed2fe1c9a4487ef2e.js:531:90552)
    at Ga (http://localhost:2746/main.f4aed2fe1c9a4487ef2e.js:531:90936)
    at Os (http://localhost:2746/main.f4aed2fe1c9a4487ef2e.js:531:97823)
    at ks (http://localhost:2746/main.f4aed2fe1c9a4487ef2e.js:531:97203)
    at Rs (http://localhost:2746/main.f4aed2fe1c9a4487ef2e.js:531:98578)
    at Tn (http://localhost:2746/main.f4aed2fe1c9a4487ef2e.js:531:30569)
Component Stack

    in Unknown
    in div
    in div
    in div
    in Unknown
    in div
    in div
    in Unknown
    in Unknown
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in t
    in Unknown
    in t
```

### Related helm chart

argo-workflows

### Helm chart version

0.16.6

### To Reproduce

Upgrade helm chart to version 3.3.8

### Expected behavior

WorkflowTemplates cannot be submitted

### Screenshots

![Uploading Screen Shot 2022-07-05 at 22.33.17.png…]()

**Comment by yu-croco** [comment]
It looks it's the same symptoms as https://github.com/argoproj/argo-helm/issues/1188 ...? 👀

**Comment by shaharl-sternum** [comment]
@yu-croco Thanks I'll look into it

**Comment by yu-croco** [comment]
Hi @shaharl-sternum , can I close this issue as duplicated ? 👀

**Comment by yu-croco** [comment]
Please re-open this issue if you need more help. 🙋
